Room DB Integration for Product List
testpress/android-sdk pull request #266
Opened 2020-08-28 07:06 UTC by SangeethaTestPress

### Changes done
- Added kotlin plugins to store
- Added Room DB to store products list
- Added MultiDex implementation

### Reason for the changes
-  the total number of references that can be invoked by the code within a single Dalvik Executable (DEX) bytecode file exceed  65536 [https://developer.android.com/studio/build/multidex]
- Added Room to support offline access.

2020-08-31 04:43 UTC, Karthik-0 commented on core/src/main/java/in/testpress/database/ProductsListDao.kt
> +}
please leave one line at the end of file

2020-08-31 04:43 UTC, Karthik-0 commented on core/src/androidTest/java/in/testpress/core/database/ProductsListDaoTest.kt
> +}
please leave one line at the end of file

2020-08-31 04:43 UTC, Karthik-0 commented on core/src/main/java/in/testpress/util/Converters.kt
> +}
please leave one line at the end of file

2020-09-01 03:32 UTC, Karthik-0 approved these changes

2020-09-03 05:43 UTC, bharathwaaj requested changes

2020-09-03 05:43 UTC, bharathwaaj commented on core/src/androidTest/java/in/testpress/core/database/ProductsListDaoTest.kt
> +    private fun createCoursesItem(): List<CoursesItem>? {
This is a fixture. Rename it accordingly.

2020-09-03 05:43 UTC, bharathwaaj commented on core/src/androidTest/java/in/testpress/core/database/ProductsListDaoTest.kt
> +    fun readWrite() {
This test case is not needed

2020-09-03 05:43 UTC, bharathwaaj commented on core/src/main/java/in/testpress/util/Converters.kt
> +        return gson.toJson(courses)
```suggestion
        return Gson().toJson(courses)
```

2020-09-03 05:43 UTC, bharathwaaj commented on core/src/main/java/in/testpress/util/Converters.kt
> +        return gson.toJson(products)
```suggestion
        return Gson().toJson(products)
```

2020-09-07 13:57 UTC, bharathwaaj approved these changes

2020-09-07 20:51 UTC, merged