Fix app crash on opening and closing a pdf
testpress/android-sdk pull request #337
Opened 2020-12-23 09:56 UTC by SangeethaTestPress

- When the PDF is clicked, then PDF will be downloaded asynchronously. So we will display loading while PDF is being downloaded. Once PDF is displayed, loading will be hidden.
 - Now the issue is if we open the PDF viewer then loading will be displayed and PDF is downloaded in the background. And if we quickly close thePDF viewer before PDF is displayed, the fragment will be closed but the downloading will be still continued as it is asynchronous. Once the download is complete it will try to hide loading progress to display PDF.
- But since the fragment is already closed, progress won't be available which leads to crash.

2021-01-08 04:28 UTC, Karthik-0 requested changes

2021-01-08 04:28 UTC, Karthik-0 commented on course/src/main/java/in/testpress/course/fragments/DocumentViewerFragment.kt
> +        progressBar.visibility = View.VISIBLE
Is this required in this PR ?

2021-01-08 04:28 UTC, Karthik-0 commented on course/src/main/java/in/testpress/course/ui/PdfViewerActivity.kt
> +        progressbar.visibility = View.VISIBLE
Is this required in this PR ?

2021-01-09 16:41 UTC, bharathwaaj approved these changes

2021-01-09 16:42 UTC, merged