Fix app crash on encrypting large PDF
testpress/android-sdk pull request #338
Opened 2020-12-23 10:28 UTC by SangeethaTestPress

- When we try to encrypt a large file (over 150 MB), the JVM will throw out of memory exception, this is due to lack of memory space(heap memory). This can be solved by allowing the JVM to allocate large heap memory.

2020-12-31 09:06 UTC, Karthik-0 requested changes

2020-12-31 09:06 UTC, Karthik-0 commented on course/src/main/java/in/testpress/course/fragments/DocumentViewerFragment.kt
> +        }
Why display pdf method is encrypting file ?

2020-12-31 09:06 UTC, Karthik-0 commented on course/src/main/java/in/testpress/course/util/FileEncryptionAndDecryption.kt
> +            return file.readBytes()
Confusing. This is not readable.

2020-12-31 09:06 UTC, Karthik-0 commented on course/src/main/java/in/testpress/course/util/FileEncryptionAndDecryption.kt
> +            val byteToReverse = getBytesCountToReverse(file)
Difficult to understand

2020-12-31 09:06 UTC, Karthik-0 commented on course/src/main/java/in/testpress/course/util/PDFDownloader.kt
> +                        file?.let { FileEncryptionAndDecryption.encrypt(it) }
This should be done in separate commit

2020-12-31 09:06 UTC, Karthik-0 commented on course/src/main/java/in/testpress/course/util/PDFDownloader.kt
> +        return file?.let { FileEncryptionAndDecryption.decrypt(it) }
.

2020-12-31 09:06 UTC, Karthik-0 commented on course/src/test/java/in/testpress/course/util/FileEncryptionAndDecryptionTest.kt
> +}
Where are the other test cases

2021-01-06 08:31 UTC, Karthik-0 requested changes

2021-01-06 08:31 UTC, Karthik-0 commented on course/src/main/java/in/testpress/course/util/FileEncryptionAndDecryption.kt
> +            val fileBytes = ByteArray(reverseByteSize)
Simplify this logic

2021-01-06 08:31 UTC, Karthik-0 commented on course/src/main/java/in/testpress/course/util/FileEncryptionAndDecryption.kt
> +class FileEncryptionAndDecryption {
You are not performing encryption/decryption. You are just reversing the file. So you can write it in separate class.

2021-01-06 08:31 UTC, Karthik-0 commented on course/src/test/java/in/testpress/course/util/FileEncryptionAndDecryptionTest.kt
> +@RunWith(RobolectricTestRunner::class)
This is unnecessary

2021-01-07 09:19 UTC, Karthik-0 requested changes

2021-01-07 09:19 UTC, Karthik-0 commented on course/src/main/java/in/testpress/course/fragments/DocumentViewerFragment.kt
> +        pdfDownloader.deleteTempFile()
Why PDF downloader is deleting temp file?

2021-01-07 09:19 UTC, Karthik-0 commented on course/src/main/java/in/testpress/course/util/FileReversal.kt
> +            randomAccessFile = RandomAccessFile(file, READ_WRITE)
This should not be initialized here

2021-01-07 09:19 UTC, Karthik-0 commented on course/src/main/java/in/testpress/course/util/FileReversal.kt
> +            goToStartOfTheFile()
This should be done in constructor

2021-01-07 09:19 UTC, Karthik-0 commented on course/src/main/java/in/testpress/course/util/FileReversal.kt
> +            randomAccessFile = RandomAccessFile(file, READ_WRITE)
This should be done in constructor

2021-01-07 09:19 UTC, Karthik-0 commented on course/src/main/java/in/testpress/course/util/FileReversal.kt
> +    }
This method is not necessary

2021-01-07 09:19 UTC, Karthik-0 commented on course/src/main/java/in/testpress/course/util/FileReversal.kt
> +        randomAccessFile.close()
This is wrong. Instance variable should be initialized before hand.

2021-01-07 09:19 UTC, Karthik-0 commented on course/src/main/java/in/testpress/course/util/FileReversal.kt
> +        tempFile.delete()
This method is not necessary. Delete temp file in deconstructor

2021-01-07 09:19 UTC, Karthik-0 commented on course/src/main/java/in/testpress/course/util/PDFDownloader.kt
>      }
Not necessary

2021-01-07 14:33 UTC, Karthik-0 requested changes

2021-01-07 14:33 UTC, Karthik-0 commented on course/src/main/java/in/testpress/course/util/FileEncryptAndDecryptUtil.kt
> +        randomAccessFile = RandomAccessFile(file, READ_WRITE)
```suggestion
        filePointer = RandomAccessFile(file, READ_WRITE)
```

2021-01-07 14:33 UTC, Karthik-0 commented on course/src/main/java/in/testpress/course/util/FileEncryptAndDecryptUtil.kt
> +    }
This can be moved inside `getBytesToReverse`

2021-01-07 14:33 UTC, Karthik-0 commented on course/src/main/java/in/testpress/course/util/FileEncryptAndDecryptUtil.kt
> +        randomAccessFile.read(byteArray)
This also can be moved inside `getBytesToReverse`

2021-01-07 14:33 UTC, Karthik-0 commented on course/src/main/java/in/testpress/course/util/FileEncryptAndDecryptUtil.kt
> +    }
This is confusing. `reverse` method should return tempFile.readBytes(). bytes should be argument to saveFile and it should be written to file.

2021-01-09 16:39 UTC, bharathwaaj requested changes

2021-01-09 16:39 UTC, bharathwaaj commented on course/src/main/java/in/testpress/course/util/FileEncryptAndDecryptUtil.kt
> +    private fun getBytesToReverse(): ByteArray {
```suggestion
    private fun getFirstFewBytesOfTheFile(): ByteArray {
```

2021-01-09 16:39 UTC, bharathwaaj commented on course/src/main/java/in/testpress/course/util/FileEncryptAndDecryptUtil.kt
> +            val bytesToReverse = getBytesToReverse()
```suggestion
            val data = getFirstFewBytesOfTheFile()
```

2021-01-09 16:39 UTC, bharathwaaj commented on course/src/main/java/in/testpress/course/util/FileEncryptAndDecryptUtil.kt
> +        val reversedData = getReversedData()
Move this inside saveReversedDataInFile

2021-01-09 16:39 UTC, bharathwaaj commented on course/src/main/java/in/testpress/course/util/FileEncryptAndDecryptUtil.kt
> +    private lateinit var tempFile: File
```suggestion
    private lateinit var tempFileToStoreReversedData: File
```

2021-01-09 16:39 UTC, bharathwaaj commented on course/src/main/java/in/testpress/course/util/FileEncryptAndDecryptUtil.kt
> +    private fun getReversedData(): ByteArray {
Not needed.

2021-01-09 16:39 UTC, bharathwaaj commented on course/src/main/java/in/testpress/course/util/FileEncryptAndDecryptUtil.kt
> +        filePointer.write(fileBytes)
```suggestion
        filePointer.write(tempFileToStoreReversedData.readBytes())
```

2021-01-09 17:46 UTC, bharathwaaj approved these changes

2021-01-09 17:47 UTC, merged