feat: Add Running Content List UI
testpress/android-sdk pull request #495
Opened 2023-03-28 09:04 UTC by PruthiviRaj27

### Changes done

2023-03-28 10:04 UTC, Karthik-0 requested changes

2023-03-28 10:08 UTC, Karthik-0 requested changes

2023-03-28 10:08 UTC, Karthik-0 commented on course/src/main/java/in/testpress/course/pagination/RunningContentRemoteMediator.kt
> +    }
Extract

2023-03-28 12:14 UTC, Karthik-0 commented on course/src/main/java/in/testpress/course/adapter/BaseContentListAdapter.kt
> +            holder.setDateAndVisiblity(
This name itself is confusing. If I am going to set a date then obviously it should be visible.

2023-03-28 12:16 UTC, Karthik-0 commented on course/src/main/java/in/testpress/course/pagination/RunningContentRemoteMediator.kt
> +            }
This can be extracted to separate method. Let it return -1 for prepend or no next page

2023-03-28 12:16 UTC, Karthik-0 commented on course/src/main/java/in/testpress/course/pagination/RunningContentRemoteMediator.kt
> +            return MediatorResult.Success(endOfPaginationReached = endOfPaginationReached)
```suggestion
            return MediatorResult.Success(endOfPaginationReached = (apiResponse.next == null))
```

2023-03-28 12:18 UTC, Karthik-0 requested changes

2023-03-28 12:18 UTC, Karthik-0 commented on course/src/main/java/in/testpress/course/util/DateUtils.kt
> +    }
Follow step down ruie

2023-03-29 07:50 UTC, Karthik-0 commented on course/src/main/java/in/testpress/course/fragments/RunningContentListFragment.kt
> +    private fun updateListView() {
Change name

2023-03-29 07:56 UTC, Karthik-0 commented on course/src/main/java/in/testpress/course/util/DateUtils.kt
> +    fun getHumanizedTimeDifferenceOrEmpty(startTimeOrEndTime: String?, context: Context): String {
```suggestion
    fun getRelativeTimeString(startTimeOrEndTime: String?, context: Context): String {
```

2023-03-30 04:31 UTC, Karthik-0 commented on course/src/main/java/in/testpress/course/fragments/RunningContentListFragment.kt
> +        observeAdapterLoadingStateAndUpdateUI()
```suggestion
        showLoadingOrContentsList()
```

2023-03-30 04:32 UTC, Karthik-0 commented on course/src/main/java/in/testpress/course/adapter/BaseContentListAdapter.kt
> +        thumbnail.setImageResource(getContentImage(content.contentType))
Extract this to a separate method. `showContentDetails`

2023-03-30 04:35 UTC, Karthik-0 commented on course/src/main/java/in/testpress/course/adapter/BaseContentListAdapter.kt
> +        setDateVisiblity(content)
Let these derived view holder override bind and display these. By default date should not be visible and if needed then viewholder will derive and display it.


Don't use `set` in method name in derived class

2023-03-30 06:16 UTC, bharathwaaj approved these changes

2023-03-30 06:18 UTC, merged